sudo: required
language: python
python:
  - "3.4"
#before_install:
#	- sudo apt-get update -qq
#	- sudo apt-get install -qq r-base
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
